// web/cloudbase-react-template/src/App.tsx
import { useEffect, useState } from "react";
import { HashRouter as Router, Routes, Route } from "react-router-dom";
import cloudbase from "./utils/cloudbase";
import HomePage from "./pages/HomePage";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

function App() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // 初始化登录
    const initAuth = async () => {
      try {
        console.log("开始登录...");
        await cloudbase.ensureLogin();
        console.log("登录成功");
      } catch (error) {
        console.error("登录失败", error);
      } finally {
        setLoading(false);
      }
    };

    initAuth();
  }, []);

  if (loading) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-base-200 text-base-content">
        <div className="loading loading-spinner loading-lg text-primary" />
        <p className="mt-4 text-sm opacity-70">加载中...</p>
      </div>
    );
  }

  return (
    <Router>
      <div className="flex min-h-screen flex-col bg-base-200 text-base-content">
        <Navbar />
        <main className="grow">
          <Routes>
            <Route path="/" element={<HomePage />} />
            {/* 可以在这里添加新的路由 */}
            <Route path="*" element={<HomePage />} />
          </Routes>
        </main>
        <Footer />
      </div>
    </Router>
  );
}

export default App;

// web/cloudbase-vue-template/src/App.vue
<template>
  <div class="flex min-h-screen flex-col bg-base-200 text-base-content">
    <div
      v-if="isLoading"
      class="flex grow flex-col items-center justify-center px-4"
    >
      <span class="loading loading-spinner loading-lg text-primary"></span>
      <p class="mt-4 text-sm opacity-70">加载中...</p>
    </div>
    <template v-else>
      <AppNavbar />
      <main class="grow">
        <RouterView />
      </main>
      <AppFooter />
    </template>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { RouterView } from "vue-router";
import AppNavbar from "./components/AppNavbar.vue";
import AppFooter from "./components/HomeFooter.vue";
import { ensureLogin } from "./utils/cloudbase.js";

const isLoading = ref(true);

onMounted(async () => {
  try {
    console.log("开始登录...");
    await ensureLogin();
    console.log("登录成功");
  } catch (error) {
    console.error("登录失败", error);
  } finally {
    isLoading.value = false;
  }
});
</script>
